### PR TITLE
Add acronym exercise

### PR DESCRIPTION
**Pull request by wasamasa**

### CODE REVIEW

**Comment by yurrriq** [comment]
Thanks!

**Comment by wasamasa** [comment]
Thanks! What's left for the exercise to appear on http://exercism.io/languages/elisp/exercises ?

**Comment by yurrriq** [comment]
IIRC @kytrinyx (or a timer) has to run a script.

**Comment by kytrinyx** [comment]
Sorry, yes I have to run a script. I was unable to do any opensource-work yesterday as I spent the day at the hospital with a family member who was undergoing surgery. I deployed this morning, and the exercise should be up now.

For [v2](https://github.com/exercism/v2-feedback/blob/master/README.md) we have a better system in place and new stuff will appear automatically within a few minutes.

**Comment by benreyn** [comment]
Im sorry to hear that @kytrinyx. Hope everything went well. Glad to hear that the system will be more automated for v2.

**Pull request merged**
