### PR TITLE
Add trinary exercise

### PR DESCRIPTION
**Pull request by wasamasa**

### CODE REVIEW

**Comment by benreyn** [comment]
I think after merging your other PR their may be some merge conflicts in `config.json`. I am also pretty sure the tests are only failing because you need to run [`configlet`](https://github.com/exercism/configlet) on this branch.

**Comment by yurrriq** [comment]
LGTM, barring the conflicts described above. Personally, I'd prefer a more pure, mutation-free solution, but the example given is certainly idiomatic.

**Comment by wasamasa** [comment]
Fixed. FWIW, `configlet lint .` showed no issues.

**Comment by benreyn** [comment]
LGTM, I think master just needed to be merged into this branch, as test are passing now. +1! Thanks for this contribution @wasamasa!

**Pull request merged**
