### PR TITLE
Fix test script

### PR DESCRIPTION
**Pull request by benreyn**

### CODE REVIEW

**Comment by benreyn** [comment]
Rebased #61 onto master to get this. Fairly certain we should see passing tests on CI now.

**Comment by benreyn** [comment]
It looks like all the the tests are actually passing on this, but for some reason CI is saying we are exiting with a code of 1 (failure) Ill take a spin on this when I get some time and see what  i can come up with.

**Comment by yurrriq** [comment]
Awesome, thanks!

**Comment by benreyn** [comment]
@yurrriq, got tests passing again and squashed this branch down to two commits. Let me know if there is anything else I can do to help!

**Comment by benreyn** [comment]
Friendly ping @yurrriq or @canweriotnow, Any chance I could get a review on this and my other open PRs?

**Comment by yurrriq** [comment]
I will do my best to review on the train or over lunch today.

**Comment by yurrriq** [comment]
LGTM thanks!

**Comment by benreyn** [comment]
Thanks @yurrriq! Now that the test script is fixed We should be able to get more exercise implemented on this track more quickly

**Pull request merged**
