### PR TITLE
Clarify instructions in Bob exercise

### PR DESCRIPTION
**Pull request by stefanv**

### CODE REVIEW

**Comment by benreyn** [comment]
Thanks for this feedback @stefanv! Ive been trying to keep us up to date with the content in the [problem-specification](https://github.com/exercism/problem-specifications) repository. Would you mind making this suggestion upstream first?

**Comment by stefanv** [comment]
OK, here you go: https://github.com/exercism/problem-specifications/pull/1516

Another thing that caught me when starting these exercises is that there was no indication of what the function should be called; indicating that you should look at the test suite may be helpful.

**Comment by benreyn** [comment]
> indicating that you should look at the test suite may be helpful.

We could be more clear about this, or provide a better blank file, perhaps with an empty function definition.

**Comment by stefanv** [comment]
https://github.com/exercism/problem-specifications/pull/1516 has now been merged.

**Comment by benreyn** [comment]
Great! Thanks @stefanv. Ill merge here now! Appreciate the contribution!

**Pull request merged**
